name: ERD PNG
on:
   push:
      branches:
        - master
      paths:
        - '*.er'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
         fetch-depth: 0

    - name: Generate PNG
      run: make build-erd

    - name: Upload PNG
      uses: actions/upload-artifact@v2
      with:
       name: 'erd'
       path: 'erd.png'

    - name: Check out code
      uses: actions/checkout@v2
      with:
         ref: 'assets'

    - name: Remove PNG
      run: rm erd.png

    - name: Download new PNG
      uses: actions/download-artifact@v2.0.5
      with:
       name: 'erd'
       path: 'erd'

    - name: Move PNG
      run: mv erd/erd.png .

    - name: Commit & Push PNG
      uses: EndBug/add-and-commit@v4
      with:
        add: 'erd.png'
        author_name: Erd Workflow
        author_email: erd@bot.com
        message: 'Update ERD diagram.'
        ref: assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

